Repository crustio/crust-sworker, pull requests merged in 2020-06, with the labels that each got.

#153 Complete new entry network
  buildenv.mk
  scripts/install_deps.sh
  src/app/ecalls/ECalls.cpp
  src/app/ecalls/ECalls.h
  src/app/http/ApiHandler.h
  src/app/ocalls/OCalls.cpp
  src/app/process/EntryNetwork.cpp
  src/app/process/Process.cpp
  src/app/process/WorkReportLoop.cpp
  src/enclave/Enclave.cpp
  src/enclave/Enclave.edl
  src/enclave/identity/Identity.cpp
  src/enclave/identity/Identity.h
  src/enclave/report/Report.cpp
  src/enclave/storage/Storage.cpp
  src/enclave/validator/Validator.cpp
  src/enclave/workload/Workload.cpp
  src/enclave/workload/Workload.h
  src/include/IASReport.h
  test/enclave/Enclave.cpp
  test/enclave/Enclave.edl
Labels: betanet, breakapi

#160 Report slot and validated proof to block attack and multiple reporting
  src/enclave/Enclave.cpp
  src/enclave/identity/Identity.cpp
  src/enclave/identity/Identity.h
  src/enclave/report/Report.cpp
  src/enclave/report/Report.h
  src/include/CrustStatus.h
Labels: betanet, bug

#161 Restart punishment
  src/app/process/WorkReportLoop.cpp
  src/enclave/identity/Identity.cpp
  src/enclave/identity/Identity.h
  src/enclave/report/Report.cpp
  src/include/CrustStatus.h
Labels: betanet, enhancement

#164 Change srd and validation process
  README.md
  src/app/config/Config.cpp
  src/app/ecalls/ECalls.cpp
  src/app/ecalls/ECalls.h
  src/app/http/ApiHandler.cpp
  src/app/http/ApiHandler.h
  src/app/ocalls/OCalls.cpp
  src/app/ocalls/OCalls.h
  src/app/process/Process.cpp
  src/app/process/Process.h
  src/app/process/Srd.cpp
  src/app/process/Srd.h
  src/app/utils/FileUtils.cpp
  src/app/utils/FileUtils.h
  src/enclave/Enclave.config.xml
  src/enclave/Enclave.cpp
  src/enclave/Enclave.edl
  src/enclave/Parameter.h
  src/enclave/identity/Identity.cpp
  src/enclave/persistence/Persistence.cpp
  src/enclave/persistence/Persistence.h
  src/enclave/report/Report.cpp
  src/enclave/srd/Srd.cpp
  src/enclave/srd/Srd.h
  src/enclave/storage/Storage.cpp
  src/enclave/utils/EUtils.cpp
  src/enclave/utils/EUtils.h
  src/enclave/validator/Validator.cpp
  src/enclave/validator/Validator.h
  src/enclave/workload/Workload.cpp
  src/enclave/workload/Workload.h
  src/include/Json.hpp
  test/enclave/utilsTest/UtilsTest.cpp
Labels: betanet, enhancement

#170 Print enclave code
  README.md
  src/enclave/identity/Identity.cpp
Labels: enhancement, maxwell

#172 Fix ecall over memory
  src/enclave/Enclave.config.xml
  src/enclave/Parameter.h
Labels: bug, maxwell

#174 Mutiple call chain and more random report time
  src/app/chain/Chain.cpp
  src/app/process/WorkReportLoop.cpp
Labels: enhancement, maxwell
