Repository crustio/crust-sworker, pull requests merged in 2020-07, with the labels that each got.

#181 Add install sgx driver shell
  README.md
  VERSION
  docker/build.sh
  docker/build_env.sh
  docker/env/Dockerfile
  docker/runner/Dockerfile
  scripts/install_deps.sh
  scripts/install_sgx_driver.sh
  src/Config.json
  src/include/CrustStatus.h
Labels: enhancement, maxwell

#185 New CI by using github action
  .github/workflows/main.yml
  README.md
Labels: enhancement, maxwell

#187 Fix some error and remove some code
  src/app/config/Config.cpp
  src/app/process/Process.cpp
  src/app/process/Srd.cpp
  src/enclave/storage/Storage.cpp
  src/include/Resource.h
Labels: bug, enhancement, maxwell

#189 Change crust tee to crust sWorker
  .gitignore
  README.md
  buildenv.mk
  docker/build.sh
  docker/build_env.sh
  docker/env/Dockerfile
  docker/runner/Dockerfile
  docker/runner/start_sworker.sh
  scripts/install.sh
  scripts/install_deps.sh
  scripts/install_sgx_driver.sh
  scripts/package.sh
  scripts/uninstall.sh
  src/Config.json
  src/app/App.cpp
  src/include/Resource.h
Labels: maxwell

#191 Remove jenkins
  Jenkinsfile
  README.md
  docker/runner/start_sworker.sh
  src/Config.json
Labels: enhancement, maxwell

#194 Fix infinite loop bug
  README.md
  src/enclave/srd/Srd.cpp
  src/enclave/validator/Validator.cpp
Labels: bug, maxwell
